/*Shrink file name*/

SELECT * FROM DBA_DATA_FILES;

SELECT FILE_NAME,
ROUND(F.BYTES / 1024 / 1024) "TOTAL SIZE M",
ROUND(F.BYTES / 1024 / 1024) - ROUND(S.BYTES / 1024 / 1024) "CAN BE SHRUNK BY M ",
'ALTER DATABASE DATAFILE ''' || FILE_NAME || ''' RESIZE ' ||
TO_CHAR(ROUND(F.BYTES / 1024 / 1024) - ROUND(S.BYTES / 1024 / 1024)) || ' M ;'
FROM DBA_DATA_FILES F, DBA_FREE_SPACE S
WHERE F.FILE_ID = S.FILE_ID
AND S.BLOCK_ID IN
(SELECT MAX(BLOCK_ID) FROM DBA_FREE_SPACE WHERE FILE_ID = S.FILE_ID)
ORDER BY 3 DESC;