/*Space from users*/

SELECT
T.TABLESPACE, 
T.TOTALSPACE AS " TOTALSPACE(MB)",
ROUND((T.TOTALSPACE-FS.FREESPACE),2) AS "USED SPACE(MB)",
FS.FREESPACE AS "FREESPACE(MB)",
ROUND(((T.TOTALSPACE-FS.FREESPACE)/T.TOTALSPACE)*100,2) AS "% USED",
ROUND((FS.FREESPACE/T.TOTALSPACE)*100,2) AS "% FREE" 
FROM
(SELECT ROUND(SUM(D.BYTES)/(1024*1024)) AS TOTALSPACE, 
D.TABLESPACE_NAME TABLESPACE 
FROM
DBA_DATA_FILES D GROUP BY D.TABLESPACE_NAME) T,
(SELECT ROUND(SUM(F.BYTES)/(1024*1024)) AS FREESPACE,
F.TABLESPACE_NAME TABLESPACE
FROM DBA_FREE_SPACE F GROUP BY F.TABLESPACE_NAME) FS
WHERE
T.TABLESPACE=FS.TABLESPACE ORDER BY T.TABLESPACE;