/*User grants exemples*/

GRANT SELECT ON USER_NAME.TABLE_NAME TO USER_NAME, USER_NAME2;
GRANT INSERT, UPDATE, SELECT, DELETE ON USER_NAME.TABLE_NAME TO USER_NAME, USER_NAME2;

GRANT EXECUTE ON USER_NAME.PROCEDURE_NAME TO USER_NAME;

GRANT DEBUG CONNECT SESSION, DEBUG ANY PROCEDURE TO USER_NAME;