SELECT USERNAME, PROGRAM, MACHINE, TO_CHAR(LOGON_TIME,'DD/MM/YYYY HH24:MI:SS'), STATUS FROM V$SESSION
WHERE USERNAME LIKE 'USER_NAME'; 

SELECT USERNAME, PROGRAM, MACHINE, TO_CHAR(LOGON_TIME,'DD/MM/YYYY HH24:MI:SS'), STATUS, LAST_CALL_ET
FROM V$SESSION WHERE USERNAME LIKE 'USER_NAME';

SELECT USERNAME, PROGRAM, MACHINE, TO_CHAR(LOGON_TIME,'DD/MM/YYYY HH24:MI:SS') FROM V$SESSION
WHERE USERNAME LIKE 'USER_NAME';