--ORACLE
/*Data Atual*/

SELECT CURRENT_DATE FROM SYS.DUAL;

/*Extrair*/

SELECT extract(DAY FROM CURRENT_DATE) FROM SYS.DUAL;
SELECT extract(MONTH FROM CURRENT_DATE) FROM SYS.DUAL;
SELECT extract(YEAR FROM CURRENT_DATE) FROM SYS.DUAL;
